[package]
name = "keyd"
version = "0.1.0"
authors = ["tyan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "*"
derive-try-from-primitive = "1.0.0"
openssl = "*"
bytes = "1.0.1"
libsshkey = { path = "../../libsshkey" }
anyhow = "1"

[[bin]]
name = "proxy"
path = "src/proxy.rs"